apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sgegrupo1
spec:
  destination:
    name: ''
    namespace: sge
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s-configuration
    repoURL: 'https://github.com/PedroRodrigues527/sd-servico-pagamentos.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
    automated:
      selfHeal: true
      prune: true
