version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadbtest
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: laravel_novo
    ports:
      - "3306:3306"