apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sge
  name: payment-service-sd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service-sd
  template:
    metadata:
      labels:
        app: payment-service-sd
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: payment-service-sd
        image: pedromiguelrodrigues/payment_service_sd:34
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  namespace: sge
  name: payment-service-sd
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
  selector:
    app: payment-service-sd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sge
  name: frontend-react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react
  template:
    metadata:
      labels:
        app: frontend-react
    spec:
      containers:
      - name: frontend-react
        image: pedromiguelrodrigues/payment_service_frontend:9
        ports:
        - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  namespace: sge
  name: frontend-react-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30003
  selector:
    app: frontend-react
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sge
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_DATABASE
          value: mydatabase
        - name: MYSQL_USER
          value: myuser
        - name: MYSQL_PASSWORD
          value: mypassword
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: sge
  name: mariadb-service
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30004
  selector:
    app: mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sge
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi