apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: sge
data:

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server:8080  
      isDefault: true
