{
 "title": "Payment service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Up time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nº de chamadas ao método GET payment",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "get_payment", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Montante gerado €",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(euros_created/100)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nº de pagamentos gerados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "payments_generated", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Montante gerado €",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "(euros_created/100)", "legendFormat": "__auto" }
   ]
  }
 ]
}