apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-pay
  namespace: sge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-pay
  template:
    metadata:
      labels:
        app: grafana-pay
    spec:
      containers:
      - name: grafana-pay
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
        - name: grafana-pay-config-volume
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: true
      volumes:
      - name: grafana-pay-config-volume
        configMap:
          name: grafana-pay-config