apiVersion: v1
kind: Service
metadata:
  name: grafana-pay
  namespace: sge
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
  selector:
    app: grafana-pay
