apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-pay-config
  namespace: sge
data:

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-pay-server:8080  
      isDefault: true
