apiVersion: v1
kind: Service
metadata:
  namespace: sge
  name: frontend-react-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30003
  selector:
    app: frontend-react