apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sge
  name: payment-service-sd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service-sd
  template:
    metadata:
      labels:
        app: payment-service-sd
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      initContainers:
      - name: migrate
        image: pedromiguelrodrigues/payment_service_sd:latest
        command: ['php', 'artisan', 'migrate']
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
      containers:
      - name: payment-service-sd
        image: pedromiguelrodrigues/payment_service_sd:latest
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"