apiVersion: v1
kind: Service
metadata:
  name: prometheus-pay-server
  namespace: sge
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: prometheus-pay-server
  type: NodePort  
  ports:
    - port: 9090
      targetPort: 9090 
      nodePort: 30005