apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-pay-server-conf
  namespace: sge
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'payment-metrics'
        static_configs:
          - targets: ['payment-service-sd:80']
        metrics_path: '/api/metric'