apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pay-server
  namespace: sge
  labels:
    app: prometheus-pay-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pay-server
  template:
    metadata:
      labels:
        app: prometheus-pay-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=120h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-data-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-pay-server-conf
        - name: prometheus-data-volume
          persistentVolumeClaim:
            claimName: prometheus-data-volume