name: Laravel

on:
  push:
    branches: [ "pre-prod" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      working-directory: ./api
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update Dependencies
      working-directory: ./api
      run: composer update
    - name: Install Dependencies
      working-directory: ./api
      run: composer install
    - name: Generate key
      working-directory: ./api
      run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ./api
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      working-directory: ./api
      run: vendor/bin/phpunit
